services:
  - type: web
    name: shivaji-library-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://kartikchhabra247_db_user:B7huO12vM9yCwX4N@cluster0.vwwd0hz.mongodb.net/shivaji_library?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: shivaji_library_super_secret_jwt_key_2026_secure
      - key: CLIENT_URL
        value: "*"